# Generated by Django 5.2.7 on 2025-11-11 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cv_manager', '0006_process'),
        ('job_analyzer', '0002_jobposting_decision'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtractionSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('POSTING', 'posting'), ('CV', 'cv')], max_length=16)),
                ('input_text', models.TextField(blank=True)),
                ('output', models.JSONField(blank=True, default=dict)),
                ('provider', models.CharField(default='stub', max_length=64)),
                ('model_name', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(choices=[('OK', 'ok'), ('ERR', 'error')], default='OK', max_length=8)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cv', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='extraction_snapshots', to='cv_manager.cv')),
                ('posting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='extraction_snapshots', to='job_analyzer.jobposting')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
