# Generated by Django 5.2.7 on 2025-11-11 21:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_bridge', '0001_initial'),
        ('cv_manager', '0006_process'),
    ]

    operations = [
        migrations.CreateModel(
            name='CVSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_text', models.TextField()),
                ('note', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='cv_manager.cv')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
