# Generated by Django 5.2.7 on 2025-12-11 18:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_bridge', '0002_cvsource'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cvsource',
            options={},
        ),
        migrations.AlterField(
            model_name='cvsource',
            name='note',
            field=models.CharField(blank=True, help_text='Örn: LinkedIn versiyonu', max_length=100),
        ),
        migrations.AlterField(
            model_name='cvsource',
            name='raw_text',
            field=models.TextField(help_text='CV içeriğini buraya yapıştırın.'),
        ),
        migrations.CreateModel(
            name='UserAISettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('openai', 'OpenAI (GPT-4o, etc.)'), ('gemini', 'Google Gemini'), ('groq', 'Groq (Llama3, Mixtral)')], default='openai', help_text='Kullanmak istediğiniz AI sağlayıcısı.', max_length=20)),
                ('api_key', models.CharField(blank=True, help_text='Seçilen sağlayıcıya ait API Anahtarı (sk-..., AIza... vb.)', max_length=255)),
                ('model_name', models.CharField(blank=True, help_text='Özel model adı (Boş bırakılırsa varsayılan kullanılır. Örn: gpt-4o-mini)', max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
