# Generated by Django 5.2.7 on 2026-01-08 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_bridge", "0003_alter_cvsource_options_alter_cvsource_note_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="useraisettings",
            name="api_key",
            field=models.CharField(
                blank=True,
                help_text="Seçilen sağlayıcıya ait API Anahtarı (şifrelenmiş olarak saklanır)",
                max_length=512,
            ),
        ),
    ]
