# Generated by Django 5.2.7 on 2026-09-12 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_bridge", "0004_alter_useraisettings_api_key"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cvsource",
            name="note",
            field=models.CharField(
                blank=True, help_text="Z. B. LinkedIn-Version", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="cvsource",
            name="raw_text",
            field=models.TextField(help_text="Fügen Sie hier den CV-Inhalt ein."),
        ),
        migrations.AlterField(
            model_name="useraisettings",
            name="api_key",
            field=models.CharField(
                blank=True,
                help_text="API-Schlüssel des ausgewählten Anbieters (wird verschlüsselt gespeichert)",
                max_length=512,
            ),
        ),
        migrations.AlterField(
            model_name="useraisettings",
            name="model_name",
            field=models.CharField(
                blank=True,
                help_text="Benutzerdefinierter Modellname (Wenn leer, wird der Standard verwendet. Z. B. gpt-4o-mini)",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="useraisettings",
            name="provider",
            field=models.CharField(
                choices=[
                    ("openai", "OpenAI (GPT-4o, etc.)"),
                    ("gemini", "Google Gemini"),
                    ("groq", "Groq (Llama3, Mixtral)"),
                ],
                default="openai",
                help_text="Der KI-Anbieter, den Sie verwenden möchten.",
                max_length=20,
            ),
        ),
    ]
