# Generated by Django 5.2.7 on 2025-11-07 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120)),
                ('field', models.CharField(choices=[('GEN', 'Allgemein'), ('BWL', 'BWL'), ('WEB', 'Webentwickler')], default='GEN', max_length=3)),
                ('is_primary', models.BooleanField(default=False, help_text='Bu alan için ana/master CV')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('github', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['full_name', 'field'],
            },
        ),
    ]
