# Generated by Django 5.2.7 on 2025-11-07 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_manager', '0003_experience'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=120)),
                ('level', models.CharField(blank=True, choices=[('basic', 'basic'), ('intermediate', 'intermediate'), ('advanced', 'advanced')], max_length=20)),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='cv_manager.cv')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('cv', 'name')},
            },
        ),
    ]
