# Generated by Django 5.2.7 on 2025-11-07 21:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_manager', '0004_skill'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('issuer', models.CharField(blank=True, max_length=160)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('expire_date', models.DateField(blank=True, null=True)),
                ('credential_id', models.CharField(blank=True, max_length=120)),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='cv_manager.cv')),
            ],
            options={
                'ordering': ['-issue_date', 'name'],
            },
        ),
    ]
