# Generated by Django 5.2.7 on 2025-11-07 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_manager', '0005_certification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('WORK_PERMIT', 'Work permit valid until'), ('UNPAID_LEAVE', 'Unpaid leave since'), ('RESIGNATION', 'Resignation completed on'), ('DL_UMSCHREIBEN', 'Driver license Umschreiben'), ('DIPLOMA_EVAL', 'Diploma evaluation'), ('BA_REG', 'Bundesagentur registration')], max_length=20)),
                ('status', models.CharField(choices=[('ONGOING', 'ongoing'), ('DONE', 'done')], default='ONGOING', max_length=10)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=240)),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processes', to='cv_manager.cv')),
            ],
            options={
                'ordering': ['type'],
            },
        ),
    ]
