# Generated by Django 5.2.7 on 2025-12-14 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_manager', '0007_cv_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='z. B. Deutsch, Englisch', max_length=50)),
                ('level', models.CharField(choices=[('A1', 'A1 – Einstieg'), ('A2', 'A2 – Grundlagen'), ('B1', 'B1 – Mittelstufe'), ('B2', 'B2 – Gute Mittelstufe'), ('C1', 'C1 – Fortgeschrittene Kenntnisse'), ('C2', 'C2 – Exzellente Kenntnisse'), ('Native', 'Muttersprache')], max_length=20)),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='languages', to='cv_manager.cv')),
            ],
            options={
                'ordering': ['-level', 'name'],
            },
        ),
    ]
