# Generated by Django 5.2.7 on 2026-01-08 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cv_manager", "0008_language"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cv",
            name="field",
            field=models.CharField(
                blank=True,
                choices=[
                    ("GEN", "Allgemein"),
                    ("BWL", "BWL"),
                    ("WEB", "Webentwickler"),
                ],
                default="GEN",
                help_text="Opsiyonel: Sadece çoklu CV kullanıyorsanız seçin",
                max_length=3,
                null=True,
            ),
        ),
    ]
