# Generated by Django 5.2.7 on 2026-04-19 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cv_manager", "0009_alter_cv_field"),
    ]

    operations = [
        migrations.AlterField(
            model_name="experience",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
