# Generated by Django 5.2.7 on 2025-11-07 22:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cv_manager', '0006_process'),
        ('job_analyzer', '0002_jobposting_decision'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cv_sections', models.JSONField(blank=True, default=dict)),
                ('cover_letter', models.TextField(blank=True)),
                ('language', models.CharField(default='de', max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drafts', to='cv_manager.cv')),
                ('posting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drafts', to='job_analyzer.jobposting')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('posting', 'cv'), name='unique_draft_per_posting_cv')],
            },
        ),
    ]
