# Generated by Django 5.2.7 on 2025-11-07 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_text', models.TextField()),
                ('target_field', models.CharField(choices=[('GEN', 'Allgemein'), ('BWL', 'BWL'), ('WEB', 'Webentwickler')], default='GEN', max_length=3)),
                ('extracted_skills', models.JSONField(blank=True, default=list)),
                ('extracted_experience', models.JSONField(blank=True, default=list)),
                ('match_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
