# Generated by Django 5.2.7 on 2025-11-07 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_analyzer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='decision',
            field=models.CharField(blank=True, choices=[('APPLY', 'apply'), ('REVIEW', 'review'), ('SKIP', 'skip')], max_length=10, null=True),
        ),
    ]
